[project]
name = "retrofun"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "alembic>=1.16.1",
    "python-dotenv>=1.1.0",
    "sqlalchemy>=2.0.41",
]
